import Controller from "../server/Controller";
import {
  ManagerCategoryController,
  AdminController,
  ManagerUserController,
  UserController,
  EmailController,
  ManagerProductController,
  ManagerBrandController,
  ManagerAddressController,
  CategoryController,
  ProductController,
  ApiAddressController,
  UserPaymentController,
  UserCartController,
  ManagerSubCategoryController,
  ManagerProductCategoryController,
  ManagerGeneralNotificationGalleryController,
  ManagerBrandGalleryController,
  ManagerCategoryGalleryController,
  ManagerSubCategoryGalleryController,
  ManagerProductGalleryController,
  ManagerUserOrderController,
  ManagerOrderController,
  ManagerPurchaseController,
  NotificationController,
  ManagerDashboardController,
  AdminTradersController,
  AdminDashboardController,
  AdminAppConfigController,
  ManagerBannerController,
  ApiBannerController,
  ApiProductsController,
  ApiFavoriteController,
  ApiCartController,
  ApiUserOrderController,
  ApiAppConfigController,
  ApiSubCategoriesController,
  ApiBrandsController,
  ApiProductCategoriesController,
  ApiNotificationController,
  ManagerFirebaseNotificationController,
  ManagerAppConfigController,
} from "./v1";

// import {
//   ManagerCategoryController as ManagerCategoryControllerV2,
//   ManagerUserController as ManagerUserControllerV2,
//   UserController as UserControllerV2,
// } from "./v2";

const controllers: Array<Controller> = [
  new ManagerBrandController(),
  new ManagerCategoryController(),
  new ManagerSubCategoryController(),
  new ManagerProductCategoryController(),
  new ManagerProductController(),
  new ManagerUserController(),
  new ManagerAddressController(),
  new ManagerOrderController(),
  new ManagerPurchaseController(),
  new ManagerUserOrderController(),
  new NotificationController(),
  new ManagerAppConfigController(),
  new ManagerDashboardController(),
  new AdminTradersController(),
  new AdminDashboardController(),
  new AdminAppConfigController(),

  new ManagerBannerController(),
  new ManagerGeneralNotificationGalleryController(),
  new ManagerBrandGalleryController(),
  new ManagerCategoryGalleryController(),
  new ManagerSubCategoryGalleryController(),
  new ManagerProductGalleryController(),
  new ManagerFirebaseNotificationController(),

  new AdminController(),
  new ApiBannerController(),
  new ApiProductsController(),
  new ApiAddressController(),
  new ApiUserOrderController(),
  new ApiFavoriteController(),
  new ApiCartController(),
  new ApiAppConfigController(),
  new ApiSubCategoriesController(),
  new ApiBrandsController(),
  new ApiProductCategoriesController(),
  new ApiNotificationController(),

  new UserController(),

  // new ManagerAddressController(),

  // new ManagerUserController(),
  // new ManagerProductController(),
  // new UserController(),
  // new EmailController(),
  // new CategoryController(),
  // new ProductController(),
  // new AddressController(),
  // new UserPaymentController(),
  // new UserCartController(),

  // new ManagerCategoryControllerV2(),
  // new ManagerUserControllerV2(),
  // new UserControllerV2(),
];

export default controllers;
